---
azs:
- name: z1
  cloud_properties: {}
- name: z2
  cloud_properties: {}

disk_types:
- name: default
  disk_size: 1024

compilation:
  workers: 5
  az: z1
  reuse_compilation_vms: true
  network: default

networks:
- name: default
  type: manual
  subnets:
  - azs: [z1, z2]
    range: 10.244.10.0/24
    static: [10.244.10.1-10.244.10.10 ]

resource_pools:
- name: default
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
